env:
  browser: true
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
extends:
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:prettier/recommended'
rules: { 'vue/multi-word-component-names': 'off' }
