
author: 
  name: Brian Sinkovec
  email: bsin1807@gmail.com

title: brian sinkovec

baseurl: ""
url: "https://briansinkovec.dev"
repository: sinkovec/sinkovec.github.io

plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - platform: envelope
      user_url: mailto:bsin1807@gmail.com
    - platform: github
      user_url: https://github.com/sinkovec
    - platform: linkedin
      user_url: https://linkedin.com/in/brian-sinkovec-9541b8242
    - platform: xing
      user_url: https://xing.com/profile/Brian_Sinkovec

header_pages:
  - missing.md

# show_excerpts: true